// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package database

import (
	"time"

	"github.com/google/uuid"
)

type History struct {
	ID        uuid.UUID
	UserID    uuid.UUID
	CreatedAt time.Time
	Prompt    string
	Reply     string
}

type User struct {
	ID        uuid.UUID
	CreatedAt time.Time
	UpdatedAt time.Time
	Name      string
}
